---
# Setup LAMP Stack
-  hosts: "{{ variable_host | default('all') }}"
   become: true
   pre_tasks:
    - pause: seconds=30
    - name: Wait for connection
      wait_for_connection:
        timeout: 300
      ignore_errors: yes
   tasks:

      - name: Install tools for adding PPA repositories
        apt:
          name: software-properties-common
          state: latest

      -  name: Add ppa repository
         apt_repository: repo=ppa:ondrej/php

      -  name: Install lamp stack
         apt:
            pkg:
              - apache2   
              - mysql-server
              - php5
              - php5-mysql   
            state: present
            update_cache: yes

      -  name: start apache server
         service: 
              name: apache2
              state: started
              enabled: yes

      -  name: start mysql service
         service:
             name: mysql
             state: started
             enabled: yes

      -  name:  create target directory
         file: path=/var/www/html state=directory mode=0755
